SELECT TOP (1000) [Id]
      ,[FirstName]
      ,[LastName]
      ,[Email]
      ,[Password]
      ,[MobileNumber]
      ,[CreatedOn]
      ,[UserType]
      ,[AccountStatus]
  FROM [LibraryMangement_Version_4].[dbo].[Users]
